---
ipv4_prefix_length: 24
start_vm: true
internal_ssh_port: 22
port_forward_protocol: TCP
vm_description: "{{ ipv4_static_address }}:{{ external_ssh_port }}"
port_forward_description: "Proxmox-VM-{{ vm_id }}"
startup_delay: 10
