#ENC[AES256_GCM,data:+dSmN/5CjVX/FSvTicn9ojpJs8hZ6/8=,iv:jehRw5o+MPCEEaTCziZE4mIv0MWgq1wfG5+mcZooFAA=,tag:7rP64NVPGp7LIaJiSf4cvA==,type:comment]
#ENC[AES256_GCM,data:MOARm6/KjPLjJKmdVAhM/2UcC8lW6J21OZyMNbV5H55G16lA8R0SlxvsAL+FF4DXDoweYr1CVMDDcBvSooXsLpfp0XPYd5r2lKc=,iv:uhOWsaI0y9gNmlAxA45h5JyDb2V6OvXqaW7S+sZpi1o=,tag:bsar1gM7toRGp6X7SLuqHw==,type:comment]
router:
    ip_address: ENC[AES256_GCM,data:AsceBNPgEPnzxEY=,iv:rRNjpGFtK1IT3aEK6NfKK9dZSJSjCKSglnYi1zoKZfY=,tag:G5U8rRlToPy/qhlQjOW7+A==,type:str]
#ENC[AES256_GCM,data:wdi+Qpk1SbM6dTtEtVEg6V3FrXwoIg==,iv:QNsqzDE8vMrtiXbUmNS6vkguJrrsGuQs5HmVJlJZzII=,tag:+rsjh1vjKEGigWX4TMlDxA==,type:comment]
proxmox:
    ip_address: ENC[AES256_GCM,data:7fzvYHDLf38JQpOg,iv:uZCq3s/OAwITm/e7BVmXdl8fP0AZUav9Ec313D5KW10=,tag:nE7X6ENyiOY4Avye/8pHcQ==,type:str]
    #ENC[AES256_GCM,data:t0b1u1JesgOLLGdQ4ZapZt9WqiQugKuOP+wQfhf1FaY/L4GW+yQI36KbszGaaW16uwxOVtsRxLOaO8rdPrF8AnVO,iv:KBQkOO3RTj9T6bRY8yrTudL0zdMtsdH78WarMBRfpcs=,tag:y8E/c1AMNEZPdzTjTXUZQw==,type:comment]
    email:
        gmail_app_username: ENC[AES256_GCM,data:DS9jkMAUwJHW2FFGghWQPNQv,iv:+RoiK0+V8iQyBvmSLdt8pogW6He7jPjtjpAIahBJiAk=,tag:KyZrg0c8vkIW0Rm1wi5tbQ==,type:str]
        gmail_app_password: ENC[AES256_GCM,data:yRCfjcgMWAnSyyGWcLDBug==,iv:pPVomYIKcXllAcZjPvN0SL5tZuNr2d4vlQZCYno48vI=,tag:YpOKOYcDwMynf7yi8HOUbA==,type:str]
        hostname: ENC[AES256_GCM,data:wjr/TwkQqISHnbc=,iv:/npfXdq7wL4yVsxKsBnqWP4OIdHmwUt/XJ5MbJ+Xodk=,tag:bbutOr/ApQEFqL2siaQ9yw==,type:str]
        #ENC[AES256_GCM,data:colu9LtTbQxzTlIxZwnyNb0jY1qB9Wr7LEKynJTacwto,iv:Mu1C3A9fvx/TcAjHu4G+Jho/+WsV2sn7nX+gZGK9jPM=,tag:lgd27vlAZhEZnTuP8bq3gA==,type:comment]
        root_alias: ENC[AES256_GCM,data:Wd0V+3x/NO558raIpa68u3o7RmuJ1TUm/LE0+oaiB31/WZI=,iv:3UJGfpcXsAO7KQ1yWr1FB4Af7ZnLkfzYzRQjOyRTNRE=,tag:qM+O2O2OtTrwnGKZxSP7PA==,type:str]
#ENC[AES256_GCM,data:R8euTaCqlsYIWjaOus+Kkmor2Jpf1FVHGxuBMdYMPVdJGLqEGvqL/pFJlX49/NmjLsXB8nnSvgp22QQWxE1tj3sip6nUFA==,iv:KkTZbMHkW1J/naRILlWbdT+CRdF6VEaa5KGhr8RS1qU=,tag:JpiyRCKVYzD86GNsLsMvXg==,type:comment]
traefik:
    ip_address: ENC[AES256_GCM,data:wvig7WCeKhoJRdO0,iv:k+FpsflssDskwMwdALs2rZ5lQMfORdOmrfL4NsemVaw=,tag:/KEnMIIPx8DWcujnVzp/4g==,type:str]
    vm_id: ENC[AES256_GCM,data:Evzs,iv:X6W0Aei7dVoLxKU+XjlNQstaLQu7ae2KUM15iyYvm8o=,tag:sER5P5t53pMoDNVyi2tNBA==,type:int]
    template_id: ENC[AES256_GCM,data:aaAp4Q==,iv:f4jDBmwStWGaXlvBq7z5uucdLvCDIz56caTWwjLBs+I=,tag:KJkoOTxDs0s6MEyo716uAw==,type:int]
    ssh_port: ENC[AES256_GCM,data:8Uy7WA==,iv:9++h7NMjE2YwpLbD/7/tOiqp0svCXkdzuCgLpEsrjHo=,tag:tl13a8ivsjTgmPhYERXRKQ==,type:int]
    routes:
        - domain: ENC[AES256_GCM,data:eWgfjK2QIGBJlHqH2NLrs3IHKVpmtNg+KA==,iv:4I1n4A+dhz58mSe7CoTmgT2YSijO1PeGUyi1MJ3hlJY=,tag:sI8oR+bCcdTF0eu0+3vhLg==,type:str]
          destination: ENC[AES256_GCM,data:4gqAG8Iq3bJyZuNC,iv:eExe7dsVGiWptCKCOBtUiJL7K8WR2FTJpKoq4svSa0w=,tag:V/BTBdYio8i/BqSTRQoU7g==,type:str]
        - domain: ENC[AES256_GCM,data:ODz9hJiB9SDm3ShW0mng8q6SMKKukzo/5kk=,iv:pCk1cw0yK6SyW9cuPvFjTm59ury5j2lrIXxgYkRq/l0=,tag:uH3fNn+FF9MunmdmBfVpTA==,type:str]
          destination: ENC[AES256_GCM,data:IR3djQHYbg0MFmDv,iv:x7B28Ttip/ltaRs42vjKPAex5kb4a1EtEbjN7onj4Sg=,tag:pleKnlAQ0JgGQHu4MAAvVA==,type:str]
#ENC[AES256_GCM,data:MzEX4Z1ARtHRi764Zeam97YbMEJxsZbPAs5PQvqP8izgAf/QhdH9,iv:UUITyDuy2qov0OXaC1BCwwaZ7dHohF2eK4QdAiYCAKE=,tag:5obOTiGO/V3FO4ektvoW4Q==,type:comment]
vm_templates:
    - name: ENC[AES256_GCM,data:+UdEQ+zKWdyY+GBpX3ESh0dd1g==,iv:F9irFbOxzEPtumIzaZUek2Oe+RExkUazZ4Nb0W2+OTU=,tag:ogIK4KcoeJXJtTVc+91hFg==,type:str]
      image_url: ENC[AES256_GCM,data:fP81HD6VfU+p3VNfpRo0fKiQ4d+0DApL0b5BC52kK2MvscPLPJFysFaeWmlxs0J3e2Ks2eijcVOUbPkB33KB5JQvBJIu9Fy8aLCgsKb4DO/3VfYFSK2Ln1HsODKTyVq4UybZFA==,iv:/m+xx+NBtHALqrqvyWZdjSuRkK7wjOLMnI93/pMFM0U=,tag:J6Bm+EH7QAGzKh21c0PSgg==,type:str]
      template_id: ENC[AES256_GCM,data:j746ag==,iv:1nLcMdD0ouC3KvttO3m+v2Tkh7o3CNka3EmibhMgPIw=,tag:xXcGcCmn4zHbEEJPaj9Pgg==,type:int]
#ENC[AES256_GCM,data:ffyU3+SR9/cUw9jfun8fG/M2AVHbMYTmJeJeD/9sVf38N/b+rFQ/bK5NksovCT0=,iv:TgjqZMn/095FInvhqF+gwVm4/fhUp+1iOgQtgifPUZc=,tag:SS+k+Eb2Py+QcEmCIcQH0Q==,type:comment]
vms:
    - name: ENC[AES256_GCM,data:pVBQ1D+cXogos9eUs+A=,iv:ZRJSUfcB+91PX3/l8+pOSM7SzXW82NRPwCrin0PPn5w=,tag:j35OlxMlWuRJ2sEQrDa0Wg==,type:str]
      domain: ENC[AES256_GCM,data:kzNxakP9IE4tjNawVFw8W9g3Wm5P/u1aeQ==,iv:Oz5c7mP9eQU4pMQNTL4iLofIj9yCuzKP68xJOydwJN8=,tag:iX8yrfHUIBGazuQKzSSTVg==,type:str]
      vm_id: ENC[AES256_GCM,data:9ghm,iv:7T/nlOJIlSp0DcTtM3GUSPYoQaK9feKxhq7/JH9UsIc=,tag:/bVnb4naeqmNK+P19PojUg==,type:int]
      template_id: ENC[AES256_GCM,data:HTp5KA==,iv:3Uv/kkltIuXBoq6TlMs0D0tCVGmX2V25ra8/A1Tg4eM=,tag:nc6DeK+aSwR2Jw8+T6JcSg==,type:int]
      ssh_port: ENC[AES256_GCM,data:EYmuaQ==,iv:CYIMG+a86xr7EJc3vPAY/9hRgu+G3wsU8Q8Bwu4razY=,tag:fqKqgNjZP9XJZ7K5pvSBxg==,type:int]
      ip_address: ENC[AES256_GCM,data:ZgGuAM+gKXfC5LRx,iv:jhxdo8BcnRnuJFe+FEcxXnIK7w1Sawb/6tDSBEd+txg=,tag:cLyWwXU4f1EuooUQDQhDYQ==,type:str]
    - name: ENC[AES256_GCM,data:04KS4CbxMUkcbrh6wOcT,iv:IoMl50BF4cpPELwbcByQH2TVD+7yhFFl4UZz9WKpkIE=,tag:3yXB7bViZ5SsloMxjBSvmg==,type:str]
      domain: ENC[AES256_GCM,data:RGPlVw3C9vz7KM+Jd7fy9nixuAfAb1RaTWc=,iv:Hp/eZ/CO14IXlk3bjCKDiUF4J41Jb9FmMFJ8RK/5LWk=,tag:SaQaJdBZIjY6l0XhOAqGOQ==,type:str]
      vm_id: ENC[AES256_GCM,data:xRJp,iv:eo/8jM4/rFFigd4jPUsq9pARCIisnBwMnLxJyxJvWfc=,tag:E3x0NPIDFFjrg14zVvTWUA==,type:int]
      template_id: ENC[AES256_GCM,data:HTp5KA==,iv:3Uv/kkltIuXBoq6TlMs0D0tCVGmX2V25ra8/A1Tg4eM=,tag:nc6DeK+aSwR2Jw8+T6JcSg==,type:int]
      ssh_port: ENC[AES256_GCM,data:dx8Szg==,iv:OwtZmVgYsV3O3xEbMO4xWmNY1TSS9acCu2wRxfJnvoI=,tag:G5NB1gB3Z8u1VO7V5DV7bA==,type:int]
      ip_address: ENC[AES256_GCM,data:4hWYLLcZM5rNGXPA,iv:iKcSXelHMid6GRorbIgTGV5FVVMVx09Guo9zO4kPaZI=,tag:WAy7sRw8e0GV2+3SMi6MIw==,type:str]
#ENC[AES256_GCM,data:SztoEMzKfQfRDY556NWKv2UN4fa/HOZsof0SoDA=,iv:kHFCHxL/2zcTAsSZo7BQq7VyP/juCz/AW6qKYWARAhk=,tag:spui2EWdx243NsBeCgtI1A==,type:comment]
defaults:
    #ENC[AES256_GCM,data:0KYW/e6nRdnUDVpWq48=,iv:exiZZH8s+C0SCUEtF9ZBdzjdi94b5pperCQGGWZQags=,tag:/1ixWmvTPPFBT1R89tRUpw==,type:comment]
    locale: ENC[AES256_GCM,data:2V9yy4sTNxMvTY8=,iv:8PyrrNyi/O5klGmKGdavvrrRauFw8F0dYWXngVPMKto=,tag:IU3LrmluEADlBPtoJD3FdA==,type:str]
    #ENC[AES256_GCM,data:3TwrIvRuCEtQbCpeMsQc/k2oLUntfZ3dPWBmGLskmFRh6vkxbKIkR8GluLoRDIeL9uX4sYAM6WdWsI1u5828Yfmwa8ks,iv:d/gnZRxC/E6oISb4rUAwW2fZjz5QOXu37S0TJinAyPk=,tag:lUeifTeeTu2lj/CWmGqZHg==,type:comment]
    ssh_public_key: ENC[AES256_GCM,data:WlpHs20Bg8vbaCYBSO5r5HLlBSejfPD246V5GNUmxtJInrYYdNIEcNTZiggFSX3vIO2C3sj2ja+FxMbMzn0/9dV8uElS8occZmMIAE2YE9xdSwWBrzivPQqwm6tC3hu5Koud,iv:9RoOtkaFnGxJ+YmAAql9oW+8n9hORIXKH+WOMh1Z+8c=,tag:GmvOzXD+lZyXoG3vrL2vYw==,type:str]
sops:
    lastmodified: "2025-09-30T12:56:32Z"
    mac: ENC[AES256_GCM,data:6H4t1aLMOHPOCGb0aFOKUaDi131/AgMLdbyiDC38g1W/tINqWnAqOnrb2HEZRm0SLM+VLAWiSYMl9DwuxXkDPdvl+n2J82DQtTcswzvPdec8LZwHvPgvfz6MXvppXjUf14CyQbcKjiyPONj8SbWLmhWkRbh7oze0A7JFI7Vck4g=,iv:8fnPREW4SptGf8j4JxGrHiRbQoqjNYrrjIoRtHU1uuo=,tag:ChxYLgc4mYPhj63amL6M/Q==,type:str]
    pgp:
        - created_at: "2025-09-28T11:57:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DuRMJhX272rcSAQdAbCEjcAsd3fVwNW7VnhPhV5j+/4AMtoU0AtW9/iVIujMw
            Pe0hbHFiTFDW52m9jxhfyIJOH6oqNME71wnDyF2OFBYX8ljgYHS/cNBzOwabft6L
            1GgBCQIQXd/ItxaO3XLdBJ/1AMMn5hbBBqgm0HaU1xiSrb2e70H5Dsp04o18+7wq
            VLEvAI+zoTYXdP4/amlfrnyoeGsENezwh/Z6fygVxuQ7CamsKA5IUi5JHajn2Cyn
            OfGNscrphpCUew==
            =dmUX
            -----END PGP MESSAGE-----
          fp: 79B39318D5DD51A12808B4478672CEE1629D465B
    unencrypted_suffix: _unencrypted
    version: 3.10.2
