ansible_host: ENC[AES256_GCM,data:jNv4jYmfqy8ptu7PxQkgeZ+JWnrTw6g/rw==,iv:P4IHqEYAxGFgbQJVUn37M2p9nul+kS/BLhbLmnJqH5c=,tag:Dazagc545UnDxwFmfbzPUQ==,type:str]
ansible_user: ENC[AES256_GCM,data:VoVeExuh1Yj3,iv:23hp4qPf4dlYBvRIr9TMWTpIAGzW6N5jA5C/ObOoo1I=,tag:yw2SV7d/gnPw273c7BkJ0Q==,type:str]
ansible_port: ENC[AES256_GCM,data:tmkr5A==,iv:4dosDIn3oSm4FVpKVX7RFlIaaIa/DbiO0iYlUndFK10=,tag:wsO1XnDt/EKYMpwyRfrptA==,type:int]
admin:
    username: ENC[AES256_GCM,data:J6XzFsY=,iv:r9J8EiCN7VB1q1SpgWN96t9oVGNC7kES12uFYhf9mos=,tag:7vVv7YgH6/DsV0YDX1mPuQ==,type:str]
    ssh_public_key: ENC[AES256_GCM,data:4fj1EZCrh8g3AsMjac+7xiDn5OflOfvxUEe0uMHIdzRPhdsmKS8Ty6jHBfwdERDm/JWKKS34/ZOXUsiNyPUNM76OJVwjt7R1ZBJi+0kmrcnvWb19eOyuLHjYKi2me9kzHdfy,iv:hcchj3OWfnE62ycr69MU8mLMuVP+cDByCc//lwDKdCY=,tag:nlO8ecKU2sGimHlbXVqNPA==,type:str]
dokku_version: ENC[AES256_GCM,data:DxNvovtTlg==,iv:ZUvM4h7OPb/56KP08qXfXftkjI5IQ3zbTMghUn3rZh8=,tag:HsIcAImT2HPX3Tf765Q/kQ==,type:str]
sops:
    lastmodified: "2025-10-04T14:18:10Z"
    mac: ENC[AES256_GCM,data:SD8UXxWgFTPCWbqSzhCuNYnSAc+vGO+aQu3l70jXWlBTCndCVPdUZQ+dAI4c++IqeEnzoyg7+c3NZkt8mZKre1PVuPzauy9nvV6F4GVGnr494M2ImpvawKS2dEPeJnPAtGPI3wqvuwvozpS2BNiub3PkzAivIdjsZ26BMJ9Yr9s=,iv:g72TYoD1BbrEqqKHcfwnbDNFkY0ra4y7OhHAmw5agZM=,tag:NhrOG3R+MpRYoKTeveUX0w==,type:str]
    pgp:
        - created_at: "2025-09-30T14:11:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DuRMJhX272rcSAQdAZM9VLdpYN9Zc5KnZ3+DPnP17C0G01wOe/VK0atYVSwMw
            14LuVW420iLOIzLkbZM3Z/SxhUXb3MJyMM7/RILACjXSN9dFFRBg997Kt8ai21qo
            1GgBCQIQvP/rlnsUAXZfasMtF2ejiqV0jmTydms2CARCp/yUBJg2wpnk6q0XZMyH
            sAVuv2B8WlwZ3mSMJj3/x9qIEN2L837dykqXATYJMpcdx/LfO+NINtSgf0xF/AW3
            mQzCw7Vua/Llxg==
            =59vl
            -----END PGP MESSAGE-----
          fp: 79B39318D5DD51A12808B4478672CEE1629D465B
    unencrypted_suffix: _unencrypted
    version: 3.10.2
