---
- name: Provision the webserver VM
  hosts: proxmox
  vars:
    vm_id: "{{ test_webserver.vm_id }}"
    template_id: "{{ vm.template_id }}"
    vm_name: test-webserver
    vm_ip_address: "{{ test_webserver.ip_address }}"
    external_ssh_port: "{{ test_webserver.ssh_port }}"
    gateway_ip_address: "{{ router.ip_address }}"
  tasks:
    - name: Provision the VM
      ansible.builtin.include_role:
        name: "provision_vm"
