---
# Ansible role to update the system packages to their latest versions

- name: Run apt update
  ansible.builtin.apt:
    update_cache: yes

#- name: Ensure all packages have latest versions
#  ansible.builtin.apt:
#    name: "*"
#    state: latest
