proxmox:
  hosts:
    proxmox-au-adelaide:
      ansible_host: au-adelaide.tombarone.net
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python3

traefik:
  hosts:
    traefik-au-adelaide:
      ansible_host: au-adelaide.tombarone.net
      ansible_user: cloudinit
      ansible_port: 9049
      ansible_python_interpreter: /usr/bin/python3

test_webserver:
  hosts:
    test-webserver-au-adelaide:
      ansible_host: au-adelaide.tombarone.net
      ansible_user: cloudinit
      ansible_port: 9050
      ansible_python_interpreter: /usr/bin/python3
